{"uuid": "ec97173d-139e-4d7b-b63c-9050d99d3e11", "children": ["eda8cd2f-de7e-41e6-9413-b3d4e60f83e0"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "AttributeError: 'Api' object has no attribute 'user_login'\n", "trace": "  File \"D:\\anaconda\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ApiTest\\test_case\\conftest.py\", line 30, in login_fixture\n    result= loginApi.login(username,password,code)\n  File \"D:\\ApiTest\\api\\login_ok.py\", line 47, in login\n    return api_util.user_login(json=json_data)\n"}, "start": 1723724117947, "stop": 1723724117953}], "start": 1723724117947, "stop": 1723724118094}